Sprinteam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kanban.urls')),
]

kanban/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as login
from . import views


urlpatterns = [
    path('', login.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', login.LogoutView.as_view(), name='logout'),
    path('cad', views.cad, name='cadastro'),
    path('boards', views.boards, name='boards'),
    path('board/<slug:name>', views.kanban, name='kanban'),
    path('board/<slug:name>/detail/<int:pk>/', views.Details, name='detail'),
    path('board/<slug:name>/detail/<int:pk>/edit', views.Edit, name='edit'),
    path('board/<slug:name>/detail/<int:pk>/delete', views.CDelete, name='delete'),
    path('board/<slug:name>/metrics', views.metrics, name='metrics'),
    path('git', views.git, name='git'),

]

kanban/models.py
from django.db import models
from django.contrib.auth.models import User
from positions import PositionField


class Teams(models.Model):
    t_name = models.CharField(max_length=100)
    t_company = models.CharField(max_length=100)
    t_details = models.CharField(max_length=400)


class Users(models.Model):
    u_name = models.OneToOneField(User, on_delete=models.CASCADE)
    u_username = models.CharField(max_length=80)
    u_email = models.CharField(max_length=80)
    u_admin = models.IntegerField(default=0)
    u_team = models.ForeignKey(Teams, on_delete=models.CASCADE, default='')


class Boards(models.Model):
    b_name = models.CharField(max_length=40)
    b_description = models.CharField(max_length=500)
    b_topics = models.CharField(max_length=10)
    b_points = models.IntegerField(default=0)
    b_icon = models.CharField(max_length=500, default='images/deficon.png')
    b_team = models.ForeignKey(Teams, on_delete=models.CASCADE, default='')

    class Meta:
        managed = False


class Lists(models.Model):
    list_name = models.CharField(max_length=30)
    list_position = models.IntegerField()
    list_board = models.ForeignKey(Boards, on_delete=models.CASCADE, default='')


class Cards(models.Model):
    c_name = models.CharField(max_length=40)
    c_description = models.CharField(max_length=500)
    c_topic = models.CharField(max_length=10)
    c_assigned = models.ForeignKey(Users, on_delete=models.CASCADE, default='')
    c_deadline = models.DateTimeField('deadline')
    c_complexity = models.IntegerField(default=1)
    c_position = PositionField()
    c_list = models.ForeignKey(Lists, on_delete=models.CASCADE, default='')
    c_board = models.ForeignKey(Boards, on_delete=models.CASCADE, default=1)


class Categories(models.Model):
    cat_name = models.CharField(max_length=20)
    cat_board = models.ForeignKey(Boards, on_delete=models.CASCADE, default='')


class Metrics(models.Model):
    date = models.DateTimeField('finish')
    complexity = models.IntegerField()

kanban/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Cards


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class CardForm(ModelForm):
    class Meta:
        model = Cards
        exclude = ('c_assigned_id', 'c_list_id', 'c_position')
#        fields = ('c_name', 'c_complexity', 'c_topic', 'c_deadline', 'c_description')

kanban/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from django.views.generic import ListView, DetailView
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Sum, Max, Min
from django.contrib.auth.decorators import login_required
from kanban.forms import SignUpForm, CardForm
from .models import Teams, Categories, Boards, Cards, Lists
from . import gitfunc


def cad(request):
    team_list = get_list_or_404(Teams)
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            username.initial = 'Username'
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('login')
    else:
        form = SignUpForm()
    return render(request, 'cad.html', {'form': form, 'team_list': team_list})


@login_required(login_url='/')
def boards(request):
    board_list = get_list_or_404(Boards)
    context = {'board_list': board_list}
    return render(request, 'baselog.html', context)


@login_required(login_url='/')
def kanban(request, *args, **kwargs):
    team = get_list_or_404(Teams)
    board_list = get_list_or_404(Boards.objects.order_by('id'))
    board = get_object_or_404(Boards, b_name=kwargs['name'].capitalize())
    lists = get_list_or_404(Lists.objects.filter(list_board_id=board.pk).order_by('list_position'))
    cards = get_list_or_404(Cards)
    points = Cards.objects.filter(c_list=3).aggregate(Sum('c_complexity'))
    complexity = Cards.objects.aggregate(Sum('c_complexity'))
    context = {'team': team, 'board': board, 'list_board': lists, 'board_list': board_list, 'complexity': complexity,
               'points': points, 'cards': cards}
    return render(request, 'kanban/cards.html', context)


@login_required(login_url='/')
def metrics(request, *args, **kwargs):
    board = get_object_or_404(Boards, b_name=kwargs['name'].capitalize(), )
    board_list = get_list_or_404(Boards.objects.order_by('id'))
    hardest = Cards.objects.filter(c_board=board.id).annotate(Min('c_complexity'))
    if hardest:
        hardest = hardest[0]
    easiest = Cards.objects.filter(c_board=board.id).annotate(Max('c_complexity')).order_by('-c_complexity')
    if easiest:
        easiest = easiest[0]
    todo = Cards.objects.filter(c_list=1, c_board=board.id).count()
    doing = Cards.objects.filter(c_list=2, c_board=board.id).count()
    done = Cards.objects.filter(c_list=3, c_board=board.id).count()
    progress = todo + doing
    count = Cards.objects.filter(c_board=board.id).count()
    avg = count + progress / 2
    calc = count - progress
    if avg == 0 & calc == 0:
        number = 0
    else:
        number = calc / avg * 100
    pie = [['A Fazer', todo], ['Fazendo', doing], ['Feito', done]]
    context = {'board': board, 'board_list': board_list, 'hardest': hardest, 'easiest': easiest, 'number': number, 'pie': pie}
    return render(request, 'metrics/metrics.html', context)


def git(request):
    list = gitfunc.getrepos()
    context = {'git': list}
    return render(request, 'testing.html', context)


@login_required(login_url='/')
def Details(request,  *args, **kwargs):
    board = get_object_or_404(Boards, b_name=kwargs['name'].capitalize(), )
    card = get_object_or_404(Cards, pk=kwargs['pk'])
    team = get_list_or_404(Teams)
    board_list = get_list_or_404(Boards)
    lists = get_list_or_404(Lists)
    context = {'team': team, 'board': board, 'list_board': lists, 'board_list': board_list, 'card': card}
    return render(request, 'kanban/details.html', context)


@login_required(login_url='/')
def Edit(request,  *args, **kwargs):
    board = get_object_or_404(Boards, b_name=kwargs['name'].capitalize())
    card = get_object_or_404(Cards, pk=kwargs['pk'],)
    team = get_list_or_404(Teams)
    board_list = get_list_or_404(Boards)
    lists = get_list_or_404(Lists)
    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            up = form.save()
            up.id = card.id
            up.save()
    else:
        form = CardForm(instance=card)
    context = {'team': team, 'board': board, 'list_board': lists, 'board_list': board_list, 'card': card, 'form': form}
    return render(request, 'kanban/edit.html', context)

@login_required(login_url='/')
def CDelete(request,   *args, **kwargs):
    board = get_object_or_404(Boards, b_name=kwargs['name'].capitalize())
    card = get_object_or_404(Cards, pk=kwargs['pk'], )
    Cards.objects.get(id=kwargs['pk']).delete()
    return redirect('/board/Primeira')

kanban/templates/base.html
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/html">
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/betastyles.css' %}">

        <!-- favicon -->
            <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
            <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
            <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
            <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
            <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
            <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
            <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
            <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
            <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">
            <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
            <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
            <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
            <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
            <meta name="msapplication-TileColor" content="#ffffff">
            <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
            <meta name="theme-color" content="#ffffff">
        <!-- favicon end-->
        <script src="{% static 'js/mainscripts.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.bundle.min.js"></script>
        <script src="{% static 'js/chartkick.js' %}"></script>
        {% block headcontent %}
        {% endblock headcontent %}
    </head>
    <body>
    {% csrf_token %}
        <div class="flexrow">
            <div class="leftarea flexcol">
                <div class="topleft">
                    <!-- Botão de logoff-->
                    <div class="logoff" onclick=location='{% url "logout" %}'><img src="{% static "images/logoff.png" %}"></div>
                </div>
                {% block leftcontent %}
                {% endblock leftcontent%}               
            </div>
            <div class="rightarea flexcol">
                {% block rightcontent %}
                {% endblock rightcontent%}
            </div>        
        </div>
    </body>
</html>

kanban/templates/baselog.html
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/html">
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/betastyles.css' %}">
    </head>
    <body>
        <div class="boardmake flexcol">
            <div class="flexrow bdmktopo">
                <div><img src=""> Sprinteam</div>
                <div></div>
                <div>[Usuário]<img></div>
            </div>
            <div class="flexrow bdmkmeio">
                <!-- Aqui você adapta o form pra fazer criação de boards-->
                
                <form method="POST" action="" class="flexcol">
                    <input type="text">nome da board
                    <input type="text">descrição da board
                    <input type="text">topicos
                    <input type="text">Score
                    <input type="submit" value="Criar">
                </form>

                <!-- Aqui você adapta a exibição pra mostrar todas as boards existentes -->
                <div class="flexcol" style="margin-left:30px">
                    {% for b in board_list %}
                    <div class="grouppick" onclick="location='{% url "kanban" b.b_name %}'">{{ b.b_name }}</div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </body>
</html>

kanban/templates/cad.html
<!DOCTYPE HTML> 
<html xmlns="http://www.w3.org/1999/html">
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/betastyles.css' %}">
        <!-- favicons -->
            <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
            <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
            <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
            <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
            <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
            <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
            <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
            <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
            <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">
            <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
            <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
            <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
            <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
            <meta name="msapplication-TileColor" content="#ffffff">
            <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
            <meta name="theme-color" content="#ffffff">
        <!-- favicon end-->
    </head>
    <body>
        <div class="logcadbg" style="background-image:url('{% static 'images/bg.jpg'%}')">
            <form class="flexcol login" style="align-items:center" method="POST">
                {% csrf_token %}
                <img src="{% static "images/sprintshoes.png" %}" width=100px>
                <div style="color:white;font-size: 24px;margin-bottom:10px">Acelere com o Sprinteam!</div>
                <div class="logcadText cadmarg" style="margin-bottom:10px !important">
                    <img src="{% static "images/user.png" %}"><p>   Nome</p>
                    {{ form.first_name }}
                </div>
                <div class="logcadText cadmarg" style="margin-bottom:10px !important">
                    <img src="{% static "images/user.png" %}"><p>   Usuário</p>
                    {{ form.username }}
                </div>
                <div class="logcadText cadmarg" style="margin-bottom:10px !important">
                    <img src="{% static "images/mail.png" %}">
                    <p>   E-Mail</p>
                    {{ form.email }}
                </div>
                <div class="logcadText cadmarg" style="margin-bottom:10px !important">
                    <img src="{% static "images/key.png" %}">
                    <p>   Senha</p>
                    {{ form.password1 }}
                </div>
                <div class="logcadText cadmarg" style="margin-bottom:10px !important">
                    <img src="{% static "images/key.png" %}">
                    <p>   Confirmação</p>
                    {{ form.password2 }}
                </div>
                <div class="flexrow">
                    <input type="submit" class="logbutton" value="CADASTRAR">
                </div>
            </form>
        </div>
    </body>
</html>

kanban/templates/cards.html
<!-- adicionar um jeito de enviar um objeto ou detalhe que possa ser utilizado para pescar os dados do card selecionado-->
{% extends "categories.html" %}
{% block cards %}
    {% for card in lists.cards_set.all %}
    <div class="card" onclick="showCard()">
        <div class="cardfbox">
            <div class="ctitle">{{ card.c_name }}</div>
            <div class="pscore">{{card.c_complexity}}</div>
        </div>
        <div class="cdesc">{{card.c_description}}</div>
        <div class="cardfbox">
            {% for card_user in card.users.all %}
            <div class="cresp">{{card_user.u_name}}</div>
            {% endfor %}
                <div class="ctopic">{{ card.c_topic }}</div>
            <div class="cdeadline">{{ card.c_deadline }}</div>
        </div>           
    </div>
    {% endfor %}
{% endblock cards %}

kanban/templates/categories.html
{% extends "postits.html" %}
{% block categories %}

<div class="flexrow">

{% for lists in list_board %}
{% block content %}
    <div class="ccateg">{{ lists.list_name }} </div>
    <div class="categbg">
            {% block cards %}
            {% endblock cards %}
    </div>
{% endblock content %}
{% endfor %}
</div>
{% endblock categories %}

kanban/templates/details.html
{% extends "postits.html" %}
{% block details %}
    <div id="cardDetail" class="chighbg flexcol">
        <div onclick="showCard()" style="text-align:right;">X</div>
        <div class="chighlight flexcol">
            <div class="chbigfield flexrow">
                <label>{{ card.c_name }}<</label>
                <label style="margin-left:20px;"> P-Score: {{card.c_complexity}}</label>
            </div>
            <div class="flexrow chbigfield">
                <label>Responsável: </label><div class="cresp">{{card.c_assigned}}</div>
                <div class="cdeadline">{{ card.c_deadline }}</div>
            </div>
            <div class="chdesc chbigfield"> {{card.c_description}}</div>
            <div class="flexrow">
                    <div class="ctopic">{{ card.c_topic }}</div>
            </div>
        </div>
    </div>
{% endblock details %}

kanban/templates/kanban/(deprecated)postits.html
<!-- Deprecated-->
<!DOCTYPE HTML>
<html xmlns="http://www.w3.org/1999/html">
    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
        <!-- favicons -->
            <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
            <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
            <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
            <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
            <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
            <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
            <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
            <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
            <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
            <link rel="icon" type="image/png" sizes="192x192" href="{% static 'favicon/android-icon-192x192.png' %}">
            <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
            <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
            <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
            <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
            <meta name="msapplication-TileColor" content="#ffffff">
            <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
            <meta name="theme-color" content="#ffffff">
        <!-- favicon end-->
        <script src="{% static 'js/mainscripts.js' %}"></script>
        <title>{% block title %}{{ board.b_name }}{% endblock %} | Sprinteam</title>
    </head>
    <body>
    {% csrf_token %}
    <div class="wholething">
        <div class="left">
            <div class="teamselect">
                <div class="flexrow">
                    {% for team in team %}
                    <div class="teampick">{{ team.t_name|first }}</div>
                    {% endfor %}
                </div>
            </div>
            <div class="groupselect flexcol">
                {% for b in board_list %}
                <div class="grouppick">{{ b.b_name }}</div>
                {% endfor %}
            </div>
            <div class="fswitchbar">
                 <!-- Will add the proper switches -->
            <div class="teampick" onclick="location.href='metrics/metrics.html'"></div>
            </div>

        </div>
        <div class="right">
            <div class="topbar">
                <div class="flexrow">
                    <div id="bicon" class="bdround">icone da board</div>
                    <div class="flexcol">
                        <div class="flexrow">
                            <div class="bdname">{{ board.b_name }}<label> - {{team.t_name}}</label></div>
                            <div class="bdsearch">Pesquisar... <img src="{% static 'images\search.png' %}"></div>
                        </div>
                        <div class="descbox flexcol">
                            <div class="desctext">{{board.b_description}}</div>
                            <div class="desctopics">#{{board.b_topics}}</div>
                        </div>
                    </div>
                    <div id="bscore" class="bdround">{{board.b_points}}</div>
                </div>
            </div>
            <div class="board">
                {% block categories %}
                {% endblock categories %}
                
                {% block  details %}
                {% endblock details %}
            </div>
        </div>
    </div>
    </body>
</html>

kanban/templates/kanban/boarddisplay.html
{% extends "base.html" %}
{% load static %}
{% block headcontent %}
    <title>{% block title %}{{ board.b_name }}{% endblock %} | Sprinteam</title>
{% endblock headcontent %}

{% block leftcontent %}
    <div class="sectionpicker flexrow">
        <div class="section"><img src="{% static "images/board.png" %}">Boards</div>
        <div class="section othersection" onclick=location="{% url "metrics" board.b_name%}"><img src="{% static "images/metrics.png" %}">Metrics</div>
    </div>
    <div class="sectioncontent">
        {% for b in board_list %}
                <div class="bdpick bdmarg" onclick=location="{% url 'kanban' b.b_name %}"><img src="{% static b.b_icon %}" height="50" width="50">{{ b.b_name }}</div>
        {% endfor %}
    </div>
{% endblock leftcontent %}

{% block rightcontent %}
    <div class="rightarea">
        <div class="topbar">
            <div class="flexrow">
                <div class="bdicon"><img src="{% static board.b_icon %}" height="85" width="85"></div>
                <div class="flexcol">
                    <div class="flexrow">
                        <div class="bdname">{{ board.b_name }}</div>
                        <div class="bdsearch">Pesquisar...<img src="{% static "images/search.png" %}">
                        </div>
                    </div>
                    <div class="descbox flexcol">
                        <div class="desctext">{{board.b_description}}</div>
                        <div class="desctopics" style="font-size: smaller">#{{board.b_topics}}</div>
                    </div>
                </div>
                <br/>
                <div class="bdscore">{{ points.c_complexity__sum }} / <br> / {{ complexity.c_complexity__sum }}</div>
            </div>
        </div>
        <div class="board">
            {% block categories %}
            {% endblock categories %}
            
            {% block  details %}
            {% endblock details %}
            <div class="expandmenu expanded flexrow">
                <div class="expmenubuts" onclick=location="{#% url "new" board.b_name%#}"><img src="{% static "images/add.png" %}"></div>
                <div class="expmenubuts"><img src="{% static "images/git.png" %}"></div>
                <div class="expmenubuts"><img src="{% static "images/recolher.png" %}"></div>
            </div>
        </div>
    </div>
{% endblock rightcontent %}

kanban/templates/kanban/boardmaking.html
<!--
{% extends "base.html" %}
{% block headcontent %}
    <title>Criar Board| Sprinteam</title>
{% endblock headcontent %}

{% block leftcontent %}
    <div class="sectionpicker flexrow">
        <div class="section"></div>
        <div class="section othersection" onclick="location.href='metrics/metrics.html'"></div>
    </div>
    <div class="sectioncontent">
        {% for b in board_list %}
                <div class="bdpick bdmarg">{{ b.b_name }}</div>
        {% endfor %}
    </div>
{% endblock leftcontent %}

{% block rightcontent %}
    <div class="rightarea">
        <div class="topbar">
            <div class="flexrow">
                <div class="bdicon">board icon</div>
                <div class="flexcol">
                    <div class="flexrow">
                        <div class="bdname">{{ board.b_name }}<label> - {{team.t_name}}</label></div>
                        <div class="bdsearch">Pesquisar... <img src="{% static 'images\search.png' %}"></div>
                    </div>
                    <div class="descbox flexcol">
                        <div class="desctext">{{board.b_description}}</div>
                        <div class="desctopics">#{{board.b_topics}}</div>
                    </div>
                </div>
                <div class="bdscore">0 / <br> / {{board.b_points}}</div>
            </div>
        </div>
        <div class="board">
            {% block categories %}
            {% endblock categories %}
            
            {% block  details %}
            {% endblock details %}
        </div>
    </div>
{% endblock rightcontent %}
-->

<!DOCTYPE HTML>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="design/styles.css">
    </head>
    <body>
        
    </body>
</html>

kanban/templates/kanban/cards.html
<!-- adicionar um jeito de enviar um objeto ou detalhe que possa ser utilizado para pescar os dados do card selecionado-->
{% extends "kanban/categories.html" %}
{% block cards %}
    {% for card in lists.cards_set.all %}
        {% if board.id == card.c_board_id %}
    <div class="card" draggable="true" onclick="location='{% url "detail" board.b_name card.id %}'">
        <div class="cardfbox">
            <div class="ctitle">{{ card.c_name }}</div>
            <div class="pscore">{{card.c_complexity}}</div>
        </div>
        <div class="cdesc">{{card.c_description}}</div>
        <div class="cardfbox">
            {% for card_user in card.users.all %}
            <div class="cresp">{{card_user.u_name}}</div>
            {% endfor %}
                <div class="ctopic">#{{ card.c_topic }}</div>
            <div class="cdeadline">{{ card.c_deadline|date:"SHORT_DATE_FORMAT" }}</div>
        </div>           
    </div>
        {% endif %}
    {% endfor %}
{% endblock cards %}

kanban/templates/kanban/categories.html
{% extends "kanban/boarddisplay.html" %}
{% block categories %}

<div class="flexrow cadmarg">
{% for lists in list_board %}
    {% block content %}
        <div class="flexcol rightgap">
            <div class="ccateg">{{ lists.list_name }} </div>
            <div class="categbg" id="cards">
                    {% block cards %}
                    {% endblock cards %}
            </div>
        </div>
    {% endblock content %}
{% endfor %}
</div>

{% endblock categories %}

kanban/templates/testing.html
<!DOCTYPE html>
<html>
<body>
<form>
  <label for="cars">Choose a Repo:</label>
  <select id="repo" name="repo">
    {% for option in git %}
    <option value="{{ option }}">{{ option }}</option>
    {% endfor %}
  </select>
  <input type="submit">
</form>

</body>
</html>